### PR TITLE
added docker init for web container

### PR DESCRIPTION
**Pull request by PiyushRaj927**
Related PR [Canasta#222](https://github.com/CanastaWiki/Canasta/pull/222)
This PR adds the docker [init](https://docs.docker.com/compose/compose-file/#init) to the web container to manage Apache and php-fpm processes as discuussed in this [comment](https://github.com/CanastaWiki/Canasta/pull/222#discussion_r1139812215).

### CODE REVIEW

**Comment by PiyushRaj927** [comment]
@jeffw16 please approve this PR.

**Comment by jeffw16** [comment]
@PiyushRaj927 I'm sure you didn't mean this on purpose, but nobody's PR is entitled to approval. Please kindly revisit your tone when asking for a code review.

**Comment by jeffw16** [comment]
If you want to remind me to take a look, there's better ways of saying it. For instance: "@jeffw16 This PR is in tandem to the previous PR you just approved. Would you have some time to take a look at it? It's very important that this is also incorporated into the Docker Compose stack."

By the way, thank you for tagging me. Just please kindly rephrase your request next time.

**Comment by PiyushRaj927** [comment]
@jeffw16, I apologize for my previous comment, it was not my intention to be disrespectful.
I understand that my request may have caused offense, I am truly sorry for that.
Thank you for showing me how to make an appropriate request. I want to assure you that I will be mindful of my request in the future.

**Comment by Justman100** [comment]
@jeffw16

What here now?

**Comment by jeffw16** [comment]
It doesn't look like we have enough community or developer support to put this plan into action. Sorry, but we can't accept this PR at the moment. It's a shame, because I really would have liked to see it happen :(

**Pull request closed without merging**
